public with sharing class AssessmentConstants {

    public static final String SESSION_IN_PROGRESS_STATUS = 'In Progress';
    public static final String SESSION_COMPLETED_STATUS = 'Completed';
    public static final String SESSION_ABANDONED_STATUS = 'Abandoned';
    public static final String QUESTION_TYPE_TRUEFALSE = 'TrueOrFalse';
    public static final String QUESTION_TYPE_DATE = 'Date';
    public static final String QUESTION_TYPE_NUMBER = 'Number';
    public static final String QUESTION_TYPE_TEXT = 'Text';
    public static final String QUESTION_TYPE_CHOICES = 'Choices';
    public static final String ITEM_TYPE_ALERT = 'Alert';
    public static final String ITEM_TYPE_MESSAGE = 'Message';
    public static final String ITEM_TYPE_DECISION = 'Decision';
    public static final String ITEM_TYPE_QUESTION = 'Question';
    public static final String AND_DECISION = 'AND';
    public static final String OR_DECISION = 'OR';
    public static final String OPERATOR_EQUAL_TO= 'Equal To';
    public static final String OPERATOR_NOT_EQUAL_TO = 'Not Equal To';
    public static final String OPERATOR_GREATER_THAN = 'Greater Than';
    public static final String OPERATOR_LESS_THAN = 'Less Than';
    public static final String EVENT_TYPE_ON_ENTRY = 'On Entry';
    public static final String EVENT_TYPE_ON_TRUE = 'On True Condition';
    public static final String EVENT_TYPE_ON_FALSE = 'On False Condition';

}
